// Better type definitions are in types.h

// Generated by gencpp from file events_repacking_tool/V_ba_bg.msg
// DO NOT EDIT!


#ifndef EVENTS_REPACKING_TOOL_MESSAGE_V_BA_BG_H
#define EVENTS_REPACKING_TOOL_MESSAGE_V_BA_BG_H


#include <string>
#include <vector>
#include <memory>


namespace events_repacking_tool
{
template <class ContainerAllocator>
struct V_ba_bg_
{
  typedef V_ba_bg_<ContainerAllocator> Type;

  V_ba_bg_()
    : ba()
    , bg()
    , Vs()
    , head()
    , g()  {
    }
  V_ba_bg_(const ContainerAllocator& _alloc)
    : ba(_alloc)
    , bg(_alloc)
    , Vs(_alloc)
    , head(_alloc)
    , g(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _ba_type;
  _ba_type ba;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _bg_type;
  _bg_type bg;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _Vs_type;
  _Vs_type Vs;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _head_type;
  _head_type head;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _g_type;
  _g_type g;

  typedef std::shared_ptr< ::events_repacking_tool::V_ba_bg_<ContainerAllocator> > Ptr;
  typedef std::shared_ptr< ::events_repacking_tool::V_ba_bg_<ContainerAllocator> const> ConstPtr;

};
}

#endif